/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container': '#1a1a1a',
        'primary': '#86bdf7',
        'on-surface-variant': '#adaaaa',
        'on-secondary-fixed-variant': '#006a35',
        'surface-container-low': '#131313',
        'secondary': '#6bfe9c',
        'on-tertiary-fixed-variant': '#7a0002',
        'on-error-container': '#ffa8a3',
        'tertiary-container': '#fe5c4a',
        'surface-bright': '#2c2c2c',
        'surface-variant': '#262626',
        'surface': '#0e0e0e',
        'outline-variant': '#484847',
        'primary-fixed': '#86bdf7',
        'on-background': '#ffffff',
        'outline': '#767575',
        'on-tertiary': '#4f0001',
        'tertiary': '#ff7765',
        'on-tertiary-fixed': '#3a0000',
        'secondary-fixed': '#6bfe9c',
        'error': '#ff716c',
        'on-error': '#490006',
        'on-primary': '#003960',
        'error-container': '#9f0519',
        'secondary-dim': '#5bef90',
        'primary-dim': '#79afe9',
        'on-secondary-fixed': '#004a23',
        'tertiary-fixed': '#ff9383',
        'on-secondary-container': '#e3ffe4',
        'on-surface': '#ffffff',
        'on-secondary': '#005f2f',
        'surface-tint': '#86bdf7',
        'tertiary-dim': '#ff7260',
        'surface-container-highest': '#262626',
        'on-tertiary-container': '#310000',
        'primary-container': '#6ea5dd',
        'on-primary-fixed': '#00223c',
        'surface-dim': '#0e0e0e',
        'secondary-container': '#006d37',
        'inverse-surface': '#fcf9f8',
        'on-primary-fixed-variant': '#00426e',
        'background': '#0e0e0e',
        'tertiary-fixed-dim': '#ff7c6a',
        'surface-container-lowest': '#000000',
        'inverse-primary': '#246297',
        'inverse-on-surface': '#565555',
        'primary-fixed-dim': '#79afe9',
        'error-dim': '#d7383b',
        'on-primary-container': '#002440',
        'surface-container-high': '#20201f',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Space Grotesk', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
};
