"""initial schema

Revision ID: 3baf424cb829
Revises: 
Create Date: 2026-08-13 16:24:46.173296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3baf424cb829'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=255), nullable=False),
    sa.Column('collection_id', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.Column('model_used', sa.String(length=255), nullable=True),
    sa.Column('sentiment_distribution', sa.JSON(), nullable=True),
    sa.Column('top_trigger_words', sa.JSON(), nullable=True),
    sa.Column('top_entities', sa.JSON(), nullable=True),
    sa.Column('rows', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_jobs_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_jobs_job_id'), ['job_id'], unique=True)

    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('raw_file', sa.String(length=500), nullable=False),
    sa.Column('collected_at_utc', sa.DateTime(), nullable=False),
    sa.Column('run_meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collections_collection_id'), ['collection_id'], unique=True)

    op.create_table('lexicon_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.Column('intensity', sa.String(length=50), nullable=True),
    sa.Column('context', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word', 'category', name='uq_word_category')
    )
    with op.batch_alter_table('lexicon_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lexicon_entries_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_lexicon_entries_word'), ['word'], unique=False)

    op.create_table('political_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=255), nullable=False),
    sa.Column('normalized_entity', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_entity', 'type', name='uq_entity_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('political_entities')
    with op.batch_alter_table('lexicon_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lexicon_entries_word'))
        batch_op.drop_index(batch_op.f('ix_lexicon_entries_category'))

    op.drop_table('lexicon_entries')
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collections_collection_id'))

    op.drop_table('collections')
    with op.batch_alter_table('analysis_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_jobs_job_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_jobs_collection_id'))

    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###
