"""add language distribution to analysis jobs

Revision ID: cb47e5508318
Revises: 3baf424cb829
Create Date: 2026-08-13 16:45:12.531518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb47e5508318'
down_revision = '3baf424cb829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language_distribution', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_jobs', schema=None) as batch_op:
        batch_op.drop_column('language_distribution')

    # ### end Alembic commands ###
